"""
Growth Module Interfaces
========================

Clean contracts for all Growth Module components.

Interfaces:
- GrowthOrchestrator.run(mode) -> RunResult
- GrowthModule.evaluate(snapshot) -> IntentPlan[]
- ViabilityEngine.assess(intent, snapshot) -> ViabilityResult
- Guardian.approve(context) -> GuardianResult
- PaperExecutor.execute(intent) -> ExecutionResult

Run Modes:
- DryRun: No execution, no positions
- RunOnce: Full execution with positions
- Replay: Load existing run (idempotent)

Idempotency:
- run_id = hash(timestamp_bucket + config_hash + market_hash)
- If run_id exists → Replay mode
- Never re-executes positions
"""

from abc import ABC, abstractmethod
from datetime import datetime, timezone
from typing import Dict, Any, Optional, List
from pydantic import BaseModel, Field
from enum import Enum
import hashlib
import json


# ============================================================
# 🔁 Run Modes
# ============================================================

class RunMode(str, Enum):
    """
    Run modes for Growth Module execution.
    
    | Mode    | Execution | Positions |
    |---------|-----------|-----------|
    | DRY_RUN | ❌        | ❌        |
    | RUN_ONCE| ✅        | ✅        |
    | REPLAY  | ❌        | ❌        |
    """
    DRY_RUN = "dry_run"    # No execution, no positions
    RUN_ONCE = "run_once"  # Full execution with positions
    REPLAY = "replay"      # Load existing run (idempotent)


class RunStatus(str, Enum):
    """Status of a run execution."""
    SUCCESS = "success"
    BLOCKED = "blocked"
    PAUSED = "paused"
    ERROR = "error"
    REPLAYED = "replayed"


# ============================================================
# 📸 Market Snapshot
# ============================================================

class MarketSnapshot(BaseModel):
    """Point-in-time market data snapshot."""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    symbol: str
    venue: str
    
    # Price data
    last_price: float
    bid: float
    ask: float
    spread_pct: float
    
    # Volatility
    atr_pct: float
    atr_14: float
    
    # Trend
    adx: float
    ma_slope_pct: float
    trend_direction: int  # -1, 0, 1
    
    # Volume
    volume_24h: float
    volume_ratio: float
    
    # Data quality
    data_age_seconds: float
    data_quality: float
    
    def get_hash(self) -> str:
        """Generate deterministic hash of market data."""
        # Round values to avoid floating point issues
        data = {
            "symbol": self.symbol,
            "venue": self.venue,
            "price": round(self.last_price, 2),
            "spread": round(self.spread_pct, 4),
            "atr": round(self.atr_pct, 4),
            "adx": round(self.adx, 1),
            "trend": self.trend_direction,
        }
        return hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()[:16]


# ============================================================
# 📋 Intent Plan
# ============================================================

class IntentOrder(BaseModel):
    """Single order intent."""
    order_id: str
    side: str  # "buy" | "sell"
    order_type: str  # "limit" | "market" | "limit_maker"
    price: float
    size_eur: float
    size_asset: float
    post_only: bool = False
    rationale: str = ""


class IntentPlan(BaseModel):
    """Trading intent plan generated by GrowthModule."""
    plan_id: str
    agent_type: str  # "MM" | "MOM"
    preset_id: str
    symbol: str
    venue: str
    
    # Orders
    orders: List[IntentOrder] = []
    
    # Scope
    capital_eur: float
    bucket: str  # "CORE" | "EDGE" | "RESERVE"
    
    # Risk
    max_loss_eur: float
    expected_edge_pct: float
    
    # Metadata
    reason_codes: List[str] = []
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ============================================================
# ✅ Viability Result
# ============================================================

class ViabilityStatus(str, Enum):
    VIABLE = "VIABLE"
    MARGINAL = "MARGINAL"
    NOT_VIABLE = "NOT_VIABLE"


class ViabilityResult(BaseModel):
    """Result from ViabilityEngine.assess()."""
    viable: bool
    status: ViabilityStatus
    
    # Edge analysis
    expected_edge_pct: float
    required_edge_pct: float
    edge_surplus_pct: float
    
    # Cost breakdown
    total_cost_pct: float
    maker_fee_pct: float
    taker_fee_pct: float
    spread_pct: float
    slippage_pct: float
    
    # Reasons
    reasons: List[str] = []
    warnings: List[str] = []


# ============================================================
# 🛡️ Guardian Result
# ============================================================

class GuardianAction(str, Enum):
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    REDUCE = "REDUCE"


class GuardianResult(BaseModel):
    """Result from Guardian.approve()."""
    allowed: bool
    action: GuardianAction
    
    # Block reason if blocked
    block_reason: Optional[str] = None
    
    # Risk state
    daily_pnl_pct: float = 0.0
    weekly_pnl_pct: float = 0.0
    kill_switch_active: bool = False
    
    # Reasons
    reasons: List[str] = []


class GuardianContext(BaseModel):
    """Context for Guardian.approve()."""
    agent_type: str
    symbol: str
    venue: str
    side: str
    amount_eur: float
    spread_pct: float
    slippage_pct: float
    expected_edge_pct: float
    data_quality: float


# ============================================================
# ⚡ Execution Result
# ============================================================

class ExecutionResult(BaseModel):
    """Result from PaperExecutor.execute()."""
    success: bool
    
    # Order stats
    orders_created: int = 0
    orders_filled: int = 0
    orders_cancelled: int = 0
    
    # PnL
    pnl_delta_eur: float = 0.0
    fees_eur: float = 0.0
    
    # Details
    order_ids: List[str] = []
    fill_ids: List[str] = []
    
    # Error
    error: Optional[str] = None


# ============================================================
# 🏁 Run Result
# ============================================================

class RunResult(BaseModel):
    """
    Complete result from GrowthOrchestrator.run().
    
    Contains all pipeline step results.
    """
    # Identity (idempotent)
    run_id: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    
    # Mode & Status
    mode: RunMode
    status: RunStatus
    is_replay: bool = False
    
    # Context
    symbol: str
    venue: str
    
    # Router decision
    regime: str = ""
    confidence: str = ""
    recommended_agent: str = ""
    recommended_preset_id: str = ""
    
    # Pipeline results
    guardian_result: Optional[GuardianResult] = None
    viability_result: Optional[ViabilityResult] = None
    intent_plans: List[IntentPlan] = []
    execution_result: Optional[ExecutionResult] = None
    
    # Summary
    orders_created: int = 0
    orders_filled: int = 0
    pnl_delta_eur: float = 0.0
    
    # Reasons
    reason_codes: List[str] = []
    block_reason: Optional[str] = None
    
    # Raw data (for debugging)
    snapshot: Optional[MarketSnapshot] = None
    
    @staticmethod
    def generate_run_id(
        timestamp_bucket: str,
        config_hash: str,
        market_hash: str,
    ) -> str:
        """
        Generate deterministic run_id for idempotency.
        
        run_id = hash(timestamp_bucket + config_hash + market_hash)
        """
        data = f"{timestamp_bucket}:{config_hash}:{market_hash}"
        return hashlib.sha256(data.encode()).hexdigest()[:24]


# ============================================================
# 🧩 Interface Definitions (Abstract Base Classes)
# ============================================================

class IGrowthOrchestrator(ABC):
    """
    Main orchestrator interface.
    
    run(mode: RunMode) -> RunResult
    """
    
    @abstractmethod
    async def run(self, mode: RunMode, symbol: str = "BTC/USDT") -> RunResult:
        """
        Execute a Growth Module run.
        
        Args:
            mode: DRY_RUN, RUN_ONCE, or REPLAY
            symbol: Trading pair
            
        Returns:
            RunResult with complete pipeline results
            
        Idempotency:
            - run_id is deterministic
            - If run_id exists, returns replay
            - Never re-executes positions
        """
        pass
    
    @abstractmethod
    async def get_run(self, run_id: str) -> Optional[RunResult]:
        """Get a run by ID (for replay)."""
        pass


class IGrowthModule(ABC):
    """
    Growth Module evaluation interface.
    
    evaluate(snapshot) -> IntentPlan[]
    """
    
    @abstractmethod
    async def evaluate(self, snapshot: MarketSnapshot) -> List[IntentPlan]:
        """
        Evaluate market snapshot and generate intent plans.
        
        Args:
            snapshot: Point-in-time market data
            
        Returns:
            List of IntentPlan (may be empty if PAUSE recommended)
        """
        pass


class IViabilityEngine(ABC):
    """
    Viability assessment interface.
    
    assess(intent, snapshot) -> ViabilityResult
    """
    
    @abstractmethod
    async def assess(
        self,
        intent: IntentPlan,
        snapshot: MarketSnapshot,
    ) -> ViabilityResult:
        """
        Assess viability of an intent plan.
        
        Args:
            intent: The trading intent plan
            snapshot: Current market data
            
        Returns:
            ViabilityResult with cost analysis
        """
        pass


class IGuardian(ABC):
    """
    Guardian approval interface.
    
    approve(context) -> GuardianResult
    """
    
    @abstractmethod
    async def approve(self, context: GuardianContext) -> GuardianResult:
        """
        Check if trade is allowed by risk rules.
        
        Args:
            context: Trade context with risk parameters
            
        Returns:
            GuardianResult with allow/block decision
        """
        pass


class IPaperExecutor(ABC):
    """
    Paper execution interface.
    
    execute(intent) -> ExecutionResult
    """
    
    @abstractmethod
    async def execute(self, intent: IntentPlan) -> ExecutionResult:
        """
        Execute intent plan in paper trading mode.
        
        Args:
            intent: The trading intent plan
            
        Returns:
            ExecutionResult with order/fill details
        """
        pass


# ============================================================
# 🧷 Idempotency Helpers
# ============================================================

def get_timestamp_bucket(granularity_minutes: int = 5) -> str:
    """
    Get timestamp bucket for idempotency.
    
    Rounds timestamp to nearest bucket (default 5 min).
    """
    now = datetime.now(timezone.utc)
    bucket_minutes = (now.minute // granularity_minutes) * granularity_minutes
    bucket_time = now.replace(minute=bucket_minutes, second=0, microsecond=0)
    return bucket_time.strftime("%Y%m%d%H%M")


def get_config_hash(config: Dict[str, Any]) -> str:
    """Generate hash of configuration."""
    return hashlib.sha256(
        json.dumps(config, sort_keys=True, default=str).encode()
    ).hexdigest()[:16]
